freebsd_instance:
  image: freebsd-14-0-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[997d79a1ed33fc4e717733f588401a3357c73380723720d2ebe73c0c199fe387ad4b92df439ea51d8ecf08a35bfb6594]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-14-0-release-amd64
  auto_cancellation: false
  stateful: false
  setup_script:
    - pkg install -y curl wget zip pkgconf cmake qt6-base qt6-tools
  test_script:
    - mkdir build ; cd build
    - cmake ..
    - make -j$(sysctl -n hw.ncpu)
    - zip --symlinks -r dsbexec_FreeBSD.zip dsbexec
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
